### PR TITLE
Subsections

### PR DESCRIPTION
**Pull request by jimzhe842**
- Added a feature with subsections
- The sidebar will display the subsections with a section, if you scroll or click on a certain subsection
- They will be hidden if scroll or click out
- I think I caught most of the bugs
- We should review as a team, if we are not comfortable adding it, then it's fine

### CODE REVIEW

**Comment by emctackett** [comment]
Great job! I didn't notice any buggy behavior on my end. :+1: 

I was wondering if instead of the subheadings just saying "Section 2.1" (for example), we should use the actual subsection titles? Like "2.2 Feature Flags".  Interested to see what everything thinks of that idea. Here is what it looks like now:
Screen Shot 2021-08-19 at 8 40 24 AM

**Comment by emctackett** [comment]
Oh, I think the sidebar on this branch might not match the sections in the main body of the write-up. This is what I noticed:

Sidebar:
4. Architectural decisions
5. Future work
6. References
7. Presentation
8. Meet the team

Main content:
5. Engineering decisions and tradeoffs
6. Future work
7. References
8. Presentation
9. Meet the team

We should make sure the numbers line up and maybe change the sidebar to say "Engineering decisions" instead of "architectural decisions"?

**Review by kaledoux — CHANGES_REQUESTED** [review]
The subsections look like they are transitioning and tracking pretty cleanly! Nice work getting that figured out!
As @emctackett noted, the nav options don't match up totally with the updated main, so that should get updated. 
Also, we should try the subsections labeled out with their respective headings vs the generic titling ("subsection 1.1").

The images aren't coming through as referenced in the updated main because this branch doesn't appear to have the updated resources. That might just get piped over with a merge though.

**Review by kaledoux — APPROVED** [review]
Looks like its all caught up!

**Pull request merged**
